PORT = "PORT"
PG_USER = "PGUSER"
PG_PASSWORD = "PGPASSWORD"
PG_HOST = "PGHOST"
PG_PORT = "PGPORT"
PG_DATABASE = "PGDATABASE"
CHECK_IN= "checkin"
CHECK_OUT = "checkout"
TASK = "task"
USER = "user"
TASK_EVENT = "TaskEvent"
TASK_MODEL = "Task"


MSG_TASK_ID_REQUIRED = "Task ID is required."
MSG_TASK_NAME_REQUIRED = "Task name is required."
MSG_USER_ID_REQUIRED = "User ID is required."
MSG_USER_NAME_REQUIRED = "User name is required."
MSG_TASK_ID_DOES_NOT_EXIST = "Task with id {} does not exist for this user."
MSG_TASK_ALREADY_CHECKED_IN = "Task {} is already checked in."
MSG_TASK_ALREADY_CHECKED_OUT = "Task {} is already checked out."
MSG_NO_ACTIVE_TASK_EVENT = "No active task to checkout."
MSG_NO_TASKS_TO_REPORT = "No tasks to report."
MSG_USER_NOT_FOUND = "User with id {} was not found."
MSG_TASK_ALREADY_EXISTS = "Task with the name {} already exists for this user."
MSG_USER_ALREADY_CHECKED_IN = "User is already checked in to task: {}"
MSG_USER_ALREADY_EXISTS = "User '{}' already exists."
